/**
 * Turns public/data/places.json into SQL you paste into the Supabase editor.
 *
 * Generating SQL rather than writing over the network on purpose: seeding needs
 * write access, write access needs a service key, and a service key bypasses RLS
 * entirely. That key should never leave the Supabase dashboard, never land in
 * this repo, and never be pasted into a chat. SQL on a clipboard needs no
 * credential at all.
 *
 * Idempotent: on conflict it updates, so re-running after a re-seed is safe.
 *
 * Run: node scripts/seed-sql.mjs > /tmp/seed.sql
 */
import { readFile } from "node:fs/promises";

const raw = await readFile(new URL("../public/data/places.json", import.meta.url), "utf8");
const places = JSON.parse(raw);

/** Postgres string literal. Doubling single quotes is the escape. */
const q = (v) => (v === undefined || v === null || v === "" ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (xs) =>
  !xs || xs.length === 0 ? "'{}'" : `array[${xs.map((x) => q(x)).join(",")}]::text[]`;

const lines = [
  "-- Generated by scripts/seed-sql.mjs — do not edit by hand.",
  `-- ${places.length} places from public/data/places.json`,
  "",
  "begin;",
  "",
];

for (const p of places) {
  lines.push(
    `insert into public.places (id, name, category, lat, lng, address, comuna, city, website, instagram, items, diet, caveat, sources) values (`,
    `  ${q(p.id)}, ${q(p.name)}, ${q(p.category)}, ${p.lat}, ${p.lng},`,
    `  ${q(p.address)}, ${q(p.comuna)}, ${q(p.city)}, ${q(p.website)}, ${q(p.instagram)},`,
    `  ${arr(p.items)}, ${q(JSON.stringify(p.diet))}::jsonb, ${q(p.caveat)}, ${arr(p.sources)}`,
    `) on conflict (id) do update set`,
    `  name = excluded.name, category = excluded.category, lat = excluded.lat, lng = excluded.lng,`,
    `  address = excluded.address, comuna = excluded.comuna, city = excluded.city,`,
    `  website = excluded.website, instagram = excluded.instagram, items = excluded.items,`,
    `  diet = excluded.diet, caveat = excluded.caveat, sources = excluded.sources;`,
    "",
  );
}

lines.push("commit;");
lines.push("");
lines.push(`-- expect: ${places.length} rows`);
lines.push("-- select count(*) from public.places;");

console.log(lines.join("\n"));
